### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by samuelh2005** [DistortedDragon1o4/voxel#3]
Adding a license will control what people can legally do with your code. Currently we *may* not be legally allowed to install your software, even though the code is public on GitHub it doesn't mean we are sure if we can use it. (see more: https://choosealicense.com/no-permission/) - *You probably do want us to use your code but the laws can't read your mind.*

Currently you are legally liable for any issues that occur, this may become an issue in the future if no license is applied (because you are the creator of this program you hold all the copyright, so *if* this program damages someone's computer, they could sue you - if you had a license, the user has to accept the terms of the license which may not include a warranty).

To add a license create a file called `LICENSE` inside the root of this repository and paste the content of the license of your choice inside it (and modify placeholders if there are any). The website https://choosealicense.com/licenses/ can help you choose a license *(there are many more then what that website provides)* - I prefer the MIT or Apache License 2.0. This will also make GitHub label this repository that it has a license *(GitHub will provide a direct link to the license and in some places allow searching repositories with a license filter)*.

**Comment by DistortedDragon1o4** [comment]
ay, is it good now?

**Comment by samuelh2005** [comment]
@DistortedDragon1o4 Yes thanks for adding one.
